~*
~*  This job builds the CDCS2 (Cyber Database Control System) product.
~*
CDCS2.
USER,INSTALL,INSTALL.
NORERUN.
SETTL,*.
SETASL,*.
SETJSL,*.
COPY,INPUT,CD2MODS.
REPLACE,CD2MODS.
BEGIN,CDCS2,INSTALL,USERF=CD2MODS.
********************************
*                              *
*            DONE              *
* CHECK DAYFILS AND/OR OUTPUT  *
* LISTING FOR SUCCESS/FAILURE  *
*                              *
********************************
EXIT.
~eor
~include ../mods/CDCS2/CD2A629.mod
