~*
~*  This job creates a MODIFY program library file named
~*  NDLOPL in the catalog of user NETADMN. The file
~*  contains the network definition of the local host.
~*
NDLOPL.
$USER,NETADMN,${../site.cfg:PASSWORDS:NETADMN:NETADMN}.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$COPY,INPUT,NDLSRC.
$REWIND,NDLSRC.
$MODIFY,P=0,N=NDLOPL,C=0,F,Z./*CREATE NDLSRC
$REPLACE,NDLOPL.
***
*** NDLOPL COMPLETE
***
EXIT.
***
*** NDLOPL FAILED
***
~eor
~include ../files/NDLSRC.txt
