~*
~*  This job builds the QU3 (QueryUpdate) product.
~*
QU3.
USER,INSTALL,INSTALL.
NORERUN.
SETTL,*.
SETASL,*.
SETJSL,*.
COPY,INPUT,QU3MODS.
REPLACE,QU3MODS.
BEGIN,QU3,INSTALL,USERF=QU3MODS.
********************************
*                              *
*            DONE              *
* CHECK DAYFILS AND/OR OUTPUT  *
* LISTING FOR SUCCESS/FAILURE  *
*                              *
********************************
EXIT.
~eor
~include ../mods/QU3/QU30732.mod
