~*
~*  This job updates the NAMSTRT file in the catalog of
~*  NETOPS to prevent NAM from starting network applications
~*  that are not used or configured for the local system.
~*
UPDNMST.
$USER,INSTALL,INSTALL.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$GET,NAMSTRT/UN=NETOPS.
$COPY,INPUT,LGO.
$REWIND,LGO.
$LIBEDIT,P=NAMSTRT,Z.
$REPLACE,NEW=NAMSTRT/UN=NETOPS.
***
*** UPDNMST COMPLETE
***
EXIT.
***
*** UPDNMST FAILED
***
~eor
~include ../files/NAMSTRT-update.txt
