~*
~*  This job updates the NAMSTRT file in the catalog of
~*  NETOPS to prevent NAM from starting network applications
~*  that are not used or configured for the local system.
~*
UNMSTRT.
USER,INSTALL,INSTALL.
NORERUN.
SETTL,*.
SETASL,*.
SETJSL,*.
GET,NAMSTRT/UN=NETOPS.
COPY,INPUT,LGO.
REWIND,LGO.
LIBEDIT,P=NAMSTRT,Z.
REPLACE,NEW=NAMSTRT/UN=NETOPS.
***
*** UNMSTRT COMPLETE
***
EXIT.
***
*** UNMSTRT FAILED
***
~eor
~include ../files/NAMSTRT-update.txt
