~*
~*  This job builds the CDCS2 (Cyber Database Control System) product.
~*
CDCS2.
$USER,INSTALL,INSTALL.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$NOEXIT.
$TMSDEF,TO=F.
$ONEXIT.
$COPYBR,INPUT,CDCSTRT.
$COPY,INPUT,CD2MODS.
$REPLACE,CD2MODS.
$BEGIN,CDCS2,INSTALL,USERF=CD2MODS.
$REPLACE,CDCSTRT=CDC.
***
*** CDCS2 COMPLETE
***
EXIT.
***
*** CDCS2 FAILED
***
~eor
~include cdcs-start.txt
~eor
~include ../mods/CDCS2/CD2A629.mod
