~*
~*  This job creates the NJF host configuration source file,
~*  HCFSRC, in the catalog of user NETADMN. The file
~*  contains the definition of the NJE network from the
~*  perspective of the local host.
~*
HCFSRC.
$USER,NETADMN,NETADMN.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$COPY,INPUT,HCFSRC.
$REPLACE,HCFSRC.
$PERMIT,HCFSRC,INSTALL=W.
***
*** HCFSRC COMPLETE
***
EXIT.
***
*** HCFSRC FAILED
***
~eor
~include ../files/HCFSRC.txt
