~*
~*  This job creates/replaces the NJFU700 file that include modsets for NJF.
~*
NJFMODS.
$USER,INSTALL,INSTALL.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$COPY,INPUT,NJFU700.
$REPLACE,NJFU700.
***
*** NJFMODS COMPLETE
***
EXIT.
***
*** NJFMODS FAILED
***
~eor
~include ../mods/NJF/NCCNJFI.mod
~eor
~include ../mods/NJF/NCCNJFL.mod
~eor
~include ../mods/NJF/BITNET.mod
~eor
~include ../mods/NJF/SAFFIX.mod
