~*
~*  This job builds the operating system. It assumes that the
~*  job modopl.job has been run previously, if needed, to 
~*  apply corrective code and customizations to the operating
~*  system source library.
~*
NOS.
$USER,INSTALL,${../site.cfg:PASSWORDS:INSTALL:INSTALL}.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$NOEXIT.
$TMSDEF,TO=F.
$ONEXIT.
$BEGIN,NOS,INSTALL.
$BEGIN,CTS,INSTALL.
$BEGIN,TMS,INSTALL.
***
*** NOS COMPLETE
***
EXIT.
***
*** NOS FAILED
***
