~*
~*  This job builds the TCPH product. TCPH provides the NOS FTP
~*  client and server applications.
~*
TCPH.
$USER,INSTALL,${../site.cfg:PASSWORDS:INSTALL:INSTALL}.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$NOEXIT.
$TMSDEF,TO=F.
$ONEXIT.
$COPY,INPUT,FTPMODS.
$REPLACE,FTPMODS.
$BEGIN,TCPH,INSTALL,USERF=FTPMODS.
***
*** TCPH COMPLETE
***
EXIT.
***
*** TCPH FAILED
***
~eor
~include ../mods/TCPH/NCCFTP.mod
