INCL    = -I..
LIBS    = -lm -lpthread -lrt
LDFLAGS = -s -L/usr/lib/arm-linux-gnueabihf

CFLAGS  = -O2 -I. $(INCL) -std=gnu99 -mcpu=cortex-a53 -mfpu=neon-fp-armv8

OBJS    =   frend2.o               \
            frend2_helpers.o       \
            ../msufrend_util.o       

frend2: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

all: frend2

clean:
	rm -f *.o frend2

.c.o:
	$(CC) $(CFLAGS) -c $*.c
