INCL    = -I..
EXTRACFLAGS = -Wno-switch -Wno-format-security
CFLAGS  = -O3 -std=gnu99 $(INCL) $(EXTRACFLAGS)
#CFLAGS  = -O0 -g -std=gnu99 $(INCL) $(EXTRACFLAGS)

OBJS    =   frend2.o               \
            frend2_helpers.o       \
            ../msufrend_util.o       

frend2: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

all: frend2

clean:
	rm -f *.o frend2

.c.o:
	$(CC) $(CFLAGS) -c $*.c
