#!/bin/sh
# start and stop the web console server
cd webterm

case "$1" in
  start)
        node ../../webterm/webterm-server -p console.pid console.json >console.log 2>&1 &
	;;
  stop)
        kill `cat console.pid`
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
