#!/bin/sh
# start and stop the RJE web service
cd ../rje-station

case "$1" in
  start)
        node rjews -p ../KRONOS2.1/rjews.pid examples/rjews.json >../KRONOS2.1/rjews.log 2>&1 &
	;;
  stop)
        kill `cat ../KRONOS2.1/rjews.pid`
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
